### ISSUE TITLE
Trace back error AttributeError: 'Manager' object has no attribute 

### ISSUE THREAD

**Issue by GaryM0101** [thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os#5]
I have SleepTk installed on a Pinetime using your updated instructions. I'm trying again after giving up on previous past attempts.

I'm getting a traceback error "AttributeError: 'Manager' object has no attribute" when launching the icon.

At the terminal I run this:

pi@raspberrypi:~/wasp-os/wasp/apps $ python -tt SleepTk.py
  File "SleepTk.py", line 17
SyntaxError: Non-ASCII character '\xc3' in file SleepTk.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Not sure if this is even related to the traceback but could be a code encoding declaration per python...IDK? I might take a stab at trying to workaround this so I'll let you know if I find anything on my end. 

Gary

**Comment by thiswillbeyourgithub** [comment]
The get and set method of wasp are not yet approved in the main branch but are in my own branch of wasp os.

Here's my PR about it : https://github.com/wasp-os/wasp-os/pull/368

Here's my branch that I use on my watch: https://github.com/thiswillbeyourgithub/wasp-os

They are used to persistently save information on the watch. In thise case : previous settings like wether "gradual wake" is checked or not.

I strongly advise not to use an outdated version of SleepTk as I might have fixed bugs since then (don't have time to check currently).

Maybe the best would be for you to apply my waspos PR to your version to have the get/set
